### ISSUE TITLE
Checking command line on gcov run

### ISSUE THREAD

**Issue by ckormanyos** [iaitelmahjoub/hash_sha256#9]
Hi Iliass (@iaitelmahjoub)

I'm checking the command line [here](https://github.com/iaitelmahjoub/hash_sha256/blob/cdddaa6abaaf9e647282fecdd8d40c06a8b62f5c/.github/workflows/hash_sha256_codecov.yml#L27).

The command line to compile/link is a bit easier/different. I think the command-line flags are a bit mixed up.

A command like this for compile/link might work better.

```
g++ -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.cpp -I. -o hash_sha256_test.exe
```

In YAML, this will look like the following:

```
${{ matrix.compiler }} -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=${{ matrix.standard }} -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.cpp -I. -o hash_sha256_test.exe
```

**Comment by ckormanyos** [comment]
Ooops... This was trickier than I had thought.

I just tried locally with the following sequence of commands:

```sh
g++ -x c++ -c -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.cpp -I. -o hash_sha256_test.o
g++ -x none -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.o -I. -lstdc++ -o hash_sha256_test.exe
./hash_sha256_test.exe
gcov --object-directory . --demangled-names ./hash_sha256_test.cpp
lcov -c --directory . --output-file coverage_unfiltered.info
lcov --remove coverage_unfiltered.info '/usr/*' --output-file coverage.info
```

And I finally got the result:

![grafik](https://user-images.githubusercontent.com/2404721/171993687-dbafd47b-c965-4381-b765-617b47b7df4c.png)

**Comment by ckormanyos** [comment]
Also one last idea... In the YAML script for code coverage, you do not really need a compiler/standard test matrix. I suggest at first simply compiling with `g++` and using `-std=c++17`. That should get the ball rolling con Codecov.

**Comment by ckormanyos** [comment]
Hi Iliass (@iaitelmahjoub) the Like command can, in fact, be simplified:

```sh
g++ -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.o -o hash_sha256_test.exe
```

**Comment by iaitelmahjoub** [comment]
Hi @ckormanyos 

Many thanks for help and clarification.

I finally got the code coverage result:

![image](https://user-images.githubusercontent.com/48915588/171997292-f15677a7-1f27-41e4-a978-eecc71bbf280.png)

For now I'm only using g++ and -std=c++17.

**Comment by ckormanyos** [comment]
> got the code coverage result

Cool. Good job @iaitelmahjoub 

I'm not entirely sure, but I think now you still need to create a login at the Codecov webpage. This [error](https://github.com/iaitelmahjoub/hash_sha256/runs/6738212343?check_suite_focus=true#step:5:32) might indicate that.

**Comment by ckormanyos** [comment]
Personally, I found it easiest to simply use your GitHub login at Codecov.

**Comment by ckormanyos** [comment]
I see you have the [first report](https://codecov.io/github/iaitelmahjoub/hash_sha256/commit/ef5f8636ff5fb9ecb64a9e7e324fc15ac4a69a5e). Awesome!

**Comment by ckormanyos** [comment]
I think you can merge to main. This establishes a baseline at Codecov. And then you can get your badge and add it to the repository's readme. Nice job!

**Comment by iaitelmahjoub** [comment]
Hi @ckormanyos 

Jap, correct ! I had to use my github login at Codecov first.

but I still don't understand why I had to use .xml format instead of .info for the coverage output file

![image](https://user-images.githubusercontent.com/48915588/172000287-20b8116c-8e7d-464d-b48c-7c6cd8a7cf16.png)

Many Thanks!!!

**Comment by ckormanyos** [comment]
> still don't understand why I had to use .xml format instead of .info

**Comment by ckormanyos** [comment]
>> still don't understand why I had to use .xml format instead of .info

> Let me take a look. I'm not sure either.

The only thing that catches my eye is the use of Ubuntu 22.04 Jammy. I couldn't se any flags that control this, however. Well anyway, it's working. I can investigate further later. But at the moment I'm not sure about the output XML format.

**Comment by ckormanyos** [comment]
I just found another difference. My CI job does actually post-run genhtml after running lcov and filtering out with lcov. So maybe the Codecov action in my case simply _finds_ the reports from genhtml. I need to investigate this further.

**Comment by iaitelmahjoub** [comment]
I just changed the output format again from .xml to .info and it worked.

Probably something was missing in the codecov setup, that's why it didn't work

Now both (.xml and .info) work fine

**Comment by iaitelmahjoub** [comment]
Many Thanks Chris !!

**Comment by ckormanyos** [comment]
Great! Should we close this issue?

**Comment by iaitelmahjoub** [comment]
yes, I already close it
